package com.example.ygd.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.ygd.greendao.ClassProj;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "classproj".
*/
public class ClassProjDao extends AbstractDao<ClassProj, Long> {

    public static final String TABLENAME = "classproj";

    /**
     * Properties of entity ClassProj.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property EndDate = new Property(1, String.class, "endDate", false, "END_DATE");
        public final static Property PhotoUri = new Property(2, String.class, "photoUri", false, "PHOTO_URI");
        public final static Property ProjId = new Property(3, String.class, "projId", false, "PROJ_ID");
        public final static Property Remark = new Property(4, String.class, "remark", false, "REMARK");
        public final static Property RgdtDate = new Property(5, String.class, "rgdtDate", false, "RGDT_DATE");
        public final static Property VedioCt = new Property(6, String.class, "vedioCt", false, "VEDIO_CT");
    };


    public ClassProjDao(DaoConfig config) {
        super(config);
    }
    
    public ClassProjDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"classproj\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"END_DATE\" TEXT," + // 1: endDate
                "\"PHOTO_URI\" TEXT," + // 2: photoUri
                "\"PROJ_ID\" TEXT," + // 3: projId
                "\"REMARK\" TEXT," + // 4: remark
                "\"RGDT_DATE\" TEXT," + // 5: rgdtDate
                "\"VEDIO_CT\" TEXT);"); // 6: vedioCt
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"classproj\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ClassProj entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String endDate = entity.getEndDate();
        if (endDate != null) {
            stmt.bindString(2, endDate);
        }
 
        String photoUri = entity.getPhotoUri();
        if (photoUri != null) {
            stmt.bindString(3, photoUri);
        }
 
        String projId = entity.getProjId();
        if (projId != null) {
            stmt.bindString(4, projId);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(5, remark);
        }
 
        String rgdtDate = entity.getRgdtDate();
        if (rgdtDate != null) {
            stmt.bindString(6, rgdtDate);
        }
 
        String vedioCt = entity.getVedioCt();
        if (vedioCt != null) {
            stmt.bindString(7, vedioCt);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ClassProj readEntity(Cursor cursor, int offset) {
        ClassProj entity = new ClassProj( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // endDate
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // photoUri
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // projId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // remark
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // rgdtDate
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // vedioCt
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ClassProj entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEndDate(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPhotoUri(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setProjId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRemark(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setRgdtDate(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setVedioCt(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ClassProj entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ClassProj entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
